### ISSUE TITLE
kv filter: support escaped quotes

### ISSUE THREAD

**Issue by untergeek** [logstash-plugins/logstash-filter-kv#2]
Migrated from JIRA: https://logstash.jira.com/browse/LOGSTASH-2272
which was replicated at https://github.com/elasticsearch/logstash/issues/1605

With the following config:
```
input { stdin { } }
filter { kv { } }
output {
  stdout {
    codec => 'json_lines'
  }
}
```
The following message:
```json
foo="bar \"baz\""
```
Should create the following output:
```json
{"message":"foo=\"bar \\\"baz\\\"\"","@version":"1","@timestamp":"1969-01-01T01:01:01.000Z","host":"host.example.net","foo":"bar \"baz\""}
```
But instead creates the following output:
```json
{"message":"foo=\"bar \\\"baz\\\"\"","@version":"1","@timestamp":"1969-01-01T01:01:01.000Z","host":"host.example.net","foo":"bar \\"}
```

**Comment by jordansissel** [comment]
confirmed this bug.

**Comment by dalegaspi** [comment]
for those who are looking for a workaround, this is what i've done (assuming `kvdata` is the source of kv pairs:
```
mutate {
	          gsub => ["kvdata","\\"","%22"]
}
kv {
		  source => "kvdata"
		  field_split => ","
}
urldecode {
		 all_fields => true
}
```
this essentially URL-escapes the escaped quote...obviously, not very efficient...but gets the job done.

**Comment by placeybordeaux** [comment]
This bug is affecting me as well. Looks like it would be a fairly simple regex change, any specific constraints on contributions?

**Comment by placeybordeaux** [comment]
Changing the [line](https://github.com/logstash-plugins/logstash-filter-kv/blob/master/lib/logstash/filters/kv.rb#L214)

From 

 valueRxString = "(?:\"([^\"]+)\"|'([^']+)'"

To

 valueRxString = "(?:\"((\\.|[^\"])+)\"|'((\\.|[^'])+)'"

Taken from this [SO post](http://stackoverflow.com/questions/249791/regex-for-quoted-string-with-escaping-quotes)

Should fix it right? If I have some time this weekend I'll look into actually testing this.

**Comment by piquadrat** [comment]
I applied the change proposed by @placeybordeaux and extended the existing test case. Unfortunately, I wasn't able to run the tests locally (not a Ruby dev myself), but the code behaves as it should in my manual tests.

Here's the diff, let me know if I should open a PR: https://github.com/logstash-plugins/logstash-filter-kv/compare/master...piquadrat:issue-2?expand=1

**Comment by NandanPhadke** [comment]
Are there any updates on this issue? Is this issue still unresolved?

**Comment by RomanYu** [comment]
hi all, is the 'escaped quote' problem still exists? i still get the bug in 'logstash-filter-kv-4.0.2'

**Comment by wanlxp** [comment]
hi all,  the 'escaped quote' problem still exists, how can i fix it ? i still get the bug in 'logstash-filter-kv-4.0.1'

**Comment by sunchanglong1991** [comment]
hi. Escaped quotes brought me parsing errors. The quotes in the value contain escaped quotes and contain the cut symbol. When parsing, the value is split by the cut character instead of using the double quotes as a whole.
My data format is:
`"\"aaaa\" bbbb /cde"`
Configured as：
`kv {
  source => "message"
  field_split => "[,\s]"
  value_split => "="
  trim_key => "\s"
  trim_value => "\""
}`

the result is:
`value = \"aaaa\"`

**Comment by geekofalltrades** [comment]
Is there any hope for this issue? One of my newer colleagues just opened an internal bug ticket because he noticed parse issues due to this bug in our logging system. I had to point him at duplicate bugs going back YEARS. We never stopped suffering from this.

**Comment by ara-mark** [comment]
It is the year 2150, the world has been collapsed, rebuilt from scratch and everyone lives happy. except for the poor souls who still have to work around the fact that logstash-kv does not support escaped quotes.

Just kidding, the issue still exists in logstash 8.17 (2024-12-12). A nice vacation time to all!

**Comment by edmocosta** [comment]
> It is the year 2150, the world has been collapsed, rebuilt from scratch and everyone lives happy. except for the poor souls who still have to work around the fact that logstash-kv does not support escaped quotes.
> 
> Just kidding, the issue still exists in logstash 8.17 (2024-12-12). A nice vacation time to all!

I guess it means Logstash will survive an apocalypse and it will still be there in 2150 😄 

---

I gave it a try using the latest plugin version, and I'm not pretty sure if the issue still persists:

```shell
# bin/logstash -e "input { stdin { } } filter { kv { } } output { stdout { codec => 'json_lines' }}"
....
[2024-12-19T11:49:00,306][INFO ][logstash.agent           ] Pipelines running {:count=>1, :running_pipelines=>[:main], :non_running_pipelines=>[]}
foo="bar \"baz\""
{"@timestamp":"2024-12-19T10:49:06.931856Z","message":"foo=\"bar \\\"baz\\\"\"","@version":"1","event":{"original":"foo=\"bar \\\"baz\\\"\""},"host":{"hostname":"Edmos-MacBook-Pro.local"},"foo":"bar \\\"baz\\\""}
test="\"aaaa\" bbbb /cde"
{"@timestamp":"2024-12-19T10:57:49.340289Z","test":"\\\"aaaa\\\" bbbb /cde","message":"test=\"\\\"aaaa\\\" bbbb /cde\"","@version":"1","event":{"original":"test=\"\\\"aaaa\\\" bbbb /cde\""},"host":{"hostname":"Edmos-MacBook-Pro.local"}}
```

Am I missing something?

Thank you!

Edit: Oh I see, there's still an issue with the extra backslashes discussed [here](https://github.com/logstash-plugins/logstash-filter-kv/pull/27#issuecomment-224835030).
